### ISSUE TITLE
カレンダーの見た目をよりよくする（2point）

### ISSUE THREAD

**Issue by masanarih0ri** [masanarih0ri/sleeple#167]
* カレンダーの前の月と次の月のグレイが濃すぎてベタッとしてしまっている
* 今日の日付の黄色が唐突な感じがする
* 曜日と日の区別がパッと見わかりづらい
* 前の月、次の月の移動のリンクがクリックできるように見えない

## 実装イメージ
<img width="443" alt="image" src="https://user-images.githubusercontent.com/20497053/204548391-1be26221-1fc7-43b7-a551-dec7b48e56e2.png">

## コードのサンプル

```css
.simple-calendar th {
    padding: 6px;
    border-bottom: 1px solid #c3d0e5;
    border-collapse: collapse;
    border-left: 1px solid #c3d0e5;
    border-right: 1px solid #c3d0e5;
    border-top: 1px solid #c3d0e5;
    box-sizing: border-box;
    text-align: center;
    font-weight: 400;
    font-size: 14px;
    background-color: #e3eaf5;
    color: #506485;
}

.simple-calendar td {
    padding: 6px;
    vertical-align: top;
    width: 14%;
    border: 1px solid #ddd;
    border-top-color: #dddddd;
    border-top-style: solid;
    border-top-width: 1px;
    border-right-color: #dddddd;
    border-right-style: solid;
    border-right-width: 1px;
    border-bottom-color: #dddddd;
    border-bottom-style: solid;
    border-bottom-width: 1px;
    border-left-color: #dddddd;
    border-left-style: solid;
    border-left-width: 1px;
    font-size: 12px;
}

.simple-calendar .prev-month {
    background-color: #f5f5f5;
}

.simple-calendar .next-month {
    background-color: #f5f5f5;
}

.simple-calendar .today {
    background-color: #fbfbf0;
    box-shadow: 0 0 0 1px #eaea97 inset;
}

/* 前の月、次の月の移動のリンク */

element.style {
    width: 38px;
    height: 38px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #8ca7d5;
    border-radius: 4px;
    font-size: 16px;
    color: #fcfcfc;
}

.log_calendar .calendar-heading {
    text-align: center;
    margin-bottom: 16px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.log_calendar .calendar-heading .calendar-title {
    font-size: 18px;
}
```

**Comment by masanarih0ri** [comment]
* カレンダーの前の月と次の月のグレイが濃すぎてベタッとしてしまっている
* 今日の日付の黄色が唐突な感じがする
* 曜日と日の区別がパッと見わかりづらい
* 前の月、次の月の移動のリンクがクリックできるように見えない

## 実装イメージ
<img width="443" alt="image" src="https://user-images.githubusercontent.com/20497053/204548391-1be26221-1fc7-43b7-a551-dec7b48e56e2.png">


## コードのサンプル

```css
.simple-calendar th {
    padding: 6px;
    border-bottom: 1px solid #c3d0e5;
    border-collapse: collapse;
    border-left: 1px solid #c3d0e5;
    border-right: 1px solid #c3d0e5;
    border-top: 1px solid #c3d0e5;
    box-sizing: border-box;
    text-align: center;
    font-weight: 400;
    font-size: 14px;
    background-color: #e3eaf5;
    color: #506485;
}

.simple-calendar td {
    padding: 6px;
    vertical-align: top;
    width: 14%;
    border: 1px solid #ddd;
    border-top-color: #dddddd;
    border-top-style: solid;
    border-top-width: 1px;
    border-right-color: #dddddd;
    border-right-style: solid;
    border-right-width: 1px;
    border-bottom-color: #dddddd;
    border-bottom-style: solid;
    border-bottom-width: 1px;
    border-left-color: #dddddd;
    border-left-style: solid;
    border-left-width: 1px;
    font-size: 12px;
}

.simple-calendar .prev-month {
    background-color: #f5f5f5;
}

.simple-calendar .next-month {
    background-color: #f5f5f5;
}

.simple-calendar .today {
    background-color: #fbfbf0;
    box-shadow: 0 0 0 1px #eaea97 inset;
}

/* 前の月、次の月の移動のリンク */

element.style {
    width: 38px;
    height: 38px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #8ca7d5;
    border-radius: 4px;
    font-size: 16px;
    color: #fcfcfc;
}

.log_calendar .calendar-heading {
    text-align: center;
    margin-bottom: 16px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.log_calendar .calendar-heading .calendar-title {
    font-size: 18px;
}
```
